Bootstrap: docker
From: debian:jessie-slim

#Includes idba, trimmomatic, samtools, bwa, bedtools, freebayes, bbmap, vcftools, htslib, ncurses, kraken2, resistomeanalyzer, rarefactionanalyzer, SNPfinder

%environment
    export LC_ALL=C

%post
    ## Jave install doesn't work, but can load java module from summit
    apt update \
    && apt install -y --no-install-recommends \
    build-essential ca-certificates sudo tcsh\
    git make automake autoconf openjdk-7-jre wget gzip unzip sed\
    zlib1g-dev curl libbz2-dev locales libncurses5-dev liblzma-dev libcurl4-openssl-dev software-properties-common apt-transport-https\
    python3-pip python3-docopt python3-pytest python-dev python3-dev\
    libcurl4-openssl-dev libssl-dev zlib1g-dev fonts-texgyre \
    gcc g++ gfortran libblas-dev liblapack-dev dos2unix\
    r-base-core r-recommended hmmer\
    && rm -rf /var/lib/apt/lists/*

    #Installing Anaconda 2 and Conda 4.5.11
    wget -c https://repo.continuum.io/archive/Anaconda2-5.3.0-Linux-x86_64.sh
    sh Anaconda2-5.3.0-Linux-x86_64.sh -bfp /usr/local

    # add bioconda channels
    conda config --add channels defaults
    conda config --add channels conda-forge
    conda config --add channels bioconda

    # install bulk of bioinformatic tools using conda
    conda create -n snp-tools snp-pipeline smalt samtools picard gatk varscan tabix bcftools bowtie2
    
    . /usr/local/bin/activate snp-tools
    
    #ln -s /usr/local/envs/snp-tools/bin/* /usr/local/bin/
    
    #Still experimenting with how to change $PATH location. 
    echo 'export PATH=$PATH:/usr/local/envs/snp-tools/bin/' >> $SINGULARITY_ENVIRONMENT
    echo 'export CLASSPATH=/usr/local/envs/snp-tools/share/varscan-2.4.4-0/VarScan.jar:$CLASSPATH' >> $SINGULARITY_ENVIRONMENT
    echo 'export CLASSPATH=/usr/local/envs/snp-tools/share/picard-2.21.4-0/picard.jar:$CLASSPATH' >> $SINGULARITY_ENVIRONMENT
    echo 'export CLASSPATH=/usr/local/envs/snp-tools/share/gatk4-4.1.4.1-0/gatk-package-4.1.4.1-local.jar:$CLASSPATH' >> $SINGULARITY_ENVIRONMENT

    # Make sure all the tools have the right permissions to use the tools
    chmod -R 777 /usr/local/


%test
    #which bwa
    #which bedtools
    #which samtools
    #which freebayes
